Dev
chingu-voyages/v9-geckos-team-08 pull request #21
Opened 2019-06-17 18:34 UTC by auxibackup

add components

2019-06-18 22:49 UTC, auxibackup commented
just added a searchbar. we need a trailer section and a calendar section before we can finalize the layout

2019-06-19 02:54 UTC, Javiercerna requested changes
It's working on my setup, but again we can't merge until you pass all the eslint checks :worried:

2019-06-19 02:55 UTC, Javiercerna commented
> just added a searchbar. we need a trailer section and a calendar section before we can finalize the layout

Ok, I'll handle the trailer section, which is #4

2019-06-25 00:48 UTC, Javiercerna approved these changes

2019-06-25 00:50 UTC, merged